# Generated by Django 4.1 on 2025-07-23 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_actor_cinemahall_genre_alter_movie_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
